// # Authoritative Europe map data: countries with default stats and adjacency lists.
// # Adjacency is symmetric (if A lists B, B lists A).
// # favoriteResource / hatedResource are populated at game-start by the AI.

export const mapData = {
  Portugal: {
    armyStrength: 80,
    morale: 70,
    adjacency: ["Spain"],
    favoriteResource: null,
    hatedResource: null,
  },
  Spain: {
    armyStrength: 1110,
    morale: 75,
    adjacency: ["Portugal", "France"],
    favoriteResource: null,
    hatedResource: null,
  },
  France: {
    armyStrength: 125,
    morale: 80,
    adjacency: ["Spain", "Belgium"], // "Germany", "Switzerland", "Italy", "United Kingdom"
    favoriteResource: null,
    hatedResource: null,
  },
  Belgium: {
    armyStrength: 85,
    morale: 72,
    adjacency: ["France", "Netherlands"], //"Germany"s
    favoriteResource: null,
    hatedResource: null,
  },
  Netherlands: {
    armyStrength: 90,
    morale: 74,
    adjacency: ["Belgium", "Germany"],
    favoriteResource: null,
    hatedResource: null,
  },
  // "Germany": {
  //     "armyStrength": 130,
  //     "morale": 82,
  //     "adjacency": ["France", "Belgium", "Netherlands", "Denmark", "Poland", "Czechia", "Austria", "Switzerland"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Switzerland": {
  //     "armyStrength": 95,
  //     "morale": 78,
  //     "adjacency": ["France", "Germany", "Austria", "Italy"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Austria": {
  //     "armyStrength": 100,
  //     "morale": 76,
  //     "adjacency": ["Germany", "Switzerland", "Italy", "Slovenia", "Hungary", "Slovakia", "Czechia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Italy": {
  //     "armyStrength": 105,
  //     "morale": 73,
  //     "adjacency": ["France", "Switzerland", "Austria", "Slovenia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Denmark": {
  //     "armyStrength": 85,
  //     "morale": 75,
  //     "adjacency": ["Germany", "Sweden"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Poland": {
  //     "armyStrength": 110,
  //     "morale": 78,
  //     "adjacency": ["Germany", "Czechia", "Slovakia", "Ukraine", "Belarus", "Lithuania"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Czechia": {
  //     "armyStrength": 90,
  //     "morale": 74,
  //     "adjacency": ["Germany", "Poland", "Slovakia", "Austria"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Slovakia": {
  //     "armyStrength": 80,
  //     "morale": 72,
  //     "adjacency": ["Czechia", "Poland", "Austria", "Hungary", "Ukraine"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Hungary": {
  //     "armyStrength": 95,
  //     "morale": 73,
  //     "adjacency": ["Austria", "Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Slovenia": {
  //     "armyStrength": 70,
  //     "morale": 71,
  //     "adjacency": ["Austria", "Italy", "Hungary", "Croatia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Croatia": {
  //     "armyStrength": 80,
  //     "morale": 72,
  //     "adjacency": ["Slovenia", "Hungary", "Serbia", "Bosnia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Bosnia": {
  //     "armyStrength": 75,
  //     "morale": 70,
  //     "adjacency": ["Croatia", "Serbia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Serbia": {
  //     "armyStrength": 90,
  //     "morale": 74,
  //     "adjacency": ["Croatia", "Hungary", "Romania", "Bulgaria", "North Macedonia", "Bosnia", "Albania"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Romania": {
  //     "armyStrength": 100,
  //     "morale": 73,
  //     "adjacency": ["Hungary", "Ukraine", "Bulgaria", "Serbia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Bulgaria": {
  //     "armyStrength": 90,
  //     "morale": 72,
  //     "adjacency": ["Romania", "Serbia", "North Macedonia", "Greece"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Greece": {
  //     "armyStrength": 95,
  //     "morale": 75,
  //     "adjacency": ["Bulgaria", "North Macedonia", "Albania"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Albania": {
  //     "armyStrength": 70,
  //     "morale": 68,
  //     "adjacency": ["Serbia", "North Macedonia", "Greece"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "North Macedonia": {
  //     "armyStrength": 65,
  //     "morale": 68,
  //     "adjacency": ["Serbia", "Bulgaria", "Greece", "Albania"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Ukraine": {
  //     "armyStrength": 115,
  //     "morale": 80,
  //     "adjacency": ["Poland", "Slovakia", "Hungary", "Romania", "Belarus"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Belarus": {
  //     "armyStrength": 95,
  //     "morale": 73,
  //     "adjacency": ["Poland", "Ukraine", "Lithuania", "Latvia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Lithuania": {
  //     "armyStrength": 80,
  //     "morale": 74,
  //     "adjacency": ["Poland", "Belarus", "Latvia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Latvia": {
  //     "armyStrength": 75,
  //     "morale": 73,
  //     "adjacency": ["Lithuania", "Belarus", "Estonia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Estonia": {
  //     "armyStrength": 70,
  //     "morale": 74,
  //     "adjacency": ["Latvia", "Finland"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Finland": {
  //     "armyStrength": 95,
  //     "morale": 80,
  //     "adjacency": ["Sweden", "Norway", "Estonia"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Sweden": {
  //     "armyStrength": 100,
  //     "morale": 78,
  //     "adjacency": ["Norway", "Finland", "Denmark"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Norway": {
  //     "armyStrength": 90,
  //     "morale": 76,
  //     "adjacency": ["Sweden", "Finland"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "United Kingdom": {
  //     "armyStrength": 120,
  //     "morale": 82,
  //     "adjacency": ["Ireland", "France"],
  //     "favoriteResource": null,
  //     "hatedResource": null,
  // },
  // "Ireland": {
  //     "armyStrength": 75,
  //     "morale": 72,
  //     "adjacency": ["United Kingdom"],
  //     "favoriteResource": null,
  //     "hatedResource ": null,
  // },
};

// Countries offered as starting positions (spread across Europe)
export const startCountries = [
  // "United Kingdom",
  "Spain",
  // "Poland",
  // "Greece",
  // "Sweden",
  // "Romania",
  // "Ukraine",
  // "Ireland",
  // "Norway",
  "Portugal",
];
