# Authoritative Europe map data: countries with default stats and adjacency lists.
# Adjacency is symmetric (if A lists B, B lists A).
# favorite_resource / hated_resource are populated at game-start by the AI.

COUNTRIES: dict[str, dict] = {
    "Portugal": {
        "army_strength": 80,
        "morale": 70,
        "adjacency": ["Spain"],
        "favorite_resource": None,
        "hated_resource": None,
    },
    "Spain": {
        "army_strength": 110,
        "morale": 75,
        "adjacency": ["Portugal", "France"],
        "favorite_resource": None,
        "hated_resource": None,
    },
    "France": {
        "army_strength": 125,
        "morale": 80,
        "adjacency": ["Spain", "Belgium",], # "Germany", "Switzerland", "Italy", "United Kingdom"
        "favorite_resource": None,
        "hated_resource": None,
    },
    "Belgium": {
        "army_strength": 85,
        "morale": 72,
        "adjacency": ["France", "Netherlands", ], #"Germany"s
        "favorite_resource": None,
        "hated_resource": None,
    },
    "Netherlands": {
        "army_strength": 90,
        "morale": 74,
        "adjacency": ["Belgium", "Germany"],
        "favorite_resource": None,
        "hated_resource": None,
    },
    # "Germany": {
    #     "army_strength": 130,
    #     "morale": 82,
    #     "adjacency": ["France", "Belgium", "Netherlands", "Denmark", "Poland", "Czechia", "Austria", "Switzerland"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Switzerland": {
    #     "army_strength": 95,
    #     "morale": 78,
    #     "adjacency": ["France", "Germany", "Austria", "Italy"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Austria": {
    #     "army_strength": 100,
    #     "morale": 76,
    #     "adjacency": ["Germany", "Switzerland", "Italy", "Slovenia", "Hungary", "Slovakia", "Czechia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Italy": {
    #     "army_strength": 105,
    #     "morale": 73,
    #     "adjacency": ["France", "Switzerland", "Austria", "Slovenia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Denmark": {
    #     "army_strength": 85,
    #     "morale": 75,
    #     "adjacency": ["Germany", "Sweden"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Poland": {
    #     "army_strength": 110,
    #     "morale": 78,
    #     "adjacency": ["Germany", "Czechia", "Slovakia", "Ukraine", "Belarus", "Lithuania"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Czechia": {
    #     "army_strength": 90,
    #     "morale": 74,
    #     "adjacency": ["Germany", "Poland", "Slovakia", "Austria"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Slovakia": {
    #     "army_strength": 80,
    #     "morale": 72,
    #     "adjacency": ["Czechia", "Poland", "Austria", "Hungary", "Ukraine"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Hungary": {
    #     "army_strength": 95,
    #     "morale": 73,
    #     "adjacency": ["Austria", "Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Slovenia": {
    #     "army_strength": 70,
    #     "morale": 71,
    #     "adjacency": ["Austria", "Italy", "Hungary", "Croatia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Croatia": {
    #     "army_strength": 80,
    #     "morale": 72,
    #     "adjacency": ["Slovenia", "Hungary", "Serbia", "Bosnia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Bosnia": {
    #     "army_strength": 75,
    #     "morale": 70,
    #     "adjacency": ["Croatia", "Serbia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Serbia": {
    #     "army_strength": 90,
    #     "morale": 74,
    #     "adjacency": ["Croatia", "Hungary", "Romania", "Bulgaria", "North Macedonia", "Bosnia", "Albania"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Romania": {
    #     "army_strength": 100,
    #     "morale": 73,
    #     "adjacency": ["Hungary", "Ukraine", "Bulgaria", "Serbia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Bulgaria": {
    #     "army_strength": 90,
    #     "morale": 72,
    #     "adjacency": ["Romania", "Serbia", "North Macedonia", "Greece"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Greece": {
    #     "army_strength": 95,
    #     "morale": 75,
    #     "adjacency": ["Bulgaria", "North Macedonia", "Albania"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Albania": {
    #     "army_strength": 70,
    #     "morale": 68,
    #     "adjacency": ["Serbia", "North Macedonia", "Greece"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "North Macedonia": {
    #     "army_strength": 65,
    #     "morale": 68,
    #     "adjacency": ["Serbia", "Bulgaria", "Greece", "Albania"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Ukraine": {
    #     "army_strength": 115,
    #     "morale": 80,
    #     "adjacency": ["Poland", "Slovakia", "Hungary", "Romania", "Belarus"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Belarus": {
    #     "army_strength": 95,
    #     "morale": 73,
    #     "adjacency": ["Poland", "Ukraine", "Lithuania", "Latvia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Lithuania": {
    #     "army_strength": 80,
    #     "morale": 74,
    #     "adjacency": ["Poland", "Belarus", "Latvia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Latvia": {
    #     "army_strength": 75,
    #     "morale": 73,
    #     "adjacency": ["Lithuania", "Belarus", "Estonia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Estonia": {
    #     "army_strength": 70,
    #     "morale": 74,
    #     "adjacency": ["Latvia", "Finland"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Finland": {
    #     "army_strength": 95,
    #     "morale": 80,
    #     "adjacency": ["Sweden", "Norway", "Estonia"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Sweden": {
    #     "army_strength": 100,
    #     "morale": 78,
    #     "adjacency": ["Norway", "Finland", "Denmark"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Norway": {
    #     "army_strength": 90,
    #     "morale": 76,
    #     "adjacency": ["Sweden", "Finland"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "United Kingdom": {
    #     "army_strength": 120,
    #     "morale": 82,
    #     "adjacency": ["Ireland", "France"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
    # "Ireland": {
    #     "army_strength": 75,
    #     "morale": 72,
    #     "adjacency": ["United Kingdom"],
    #     "favorite_resource": None,
    #     "hated_resource": None,
    # },
}

# Countries offered as starting positions (spread across Europe)
START_COUNTRIES = [
    # "United Kingdom",
    "Spain",
    # "Poland",
    # "Greece",
    # "Sweden",
    # "Romania",
    # "Ukraine",
    # "Ireland",
    # "Norway",
    "Portugal",
]
